services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db2

    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rick2003@
      POSTGRES_DB: GerenciadorDePedidos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



  backend:
    build: ./backend
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: senha123
      DATABASE_DB: GerenciadorDePedidos
      DATABASE_PORT: 5432
    depends_on:
      - postgres_db
    ports:
      - "3001:3001"


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data:
